
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # 에러 메시지 관리
  messages:
    basename: message
    encoding: UTF-8

  jpa:
#    database-platform: org.hibernate.dialect.MariaDB103Dialect   //MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate: true
      format-sql: true
      ddl_auto: none

jwt:
  header: Authorization
  secret-key: ${JWT_SECRET-KEY}
  token-validity-in-seconds: ${JWT_SECRET-TIME} # 1시간

# spring swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs # Open api 문서 경로 변경\
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로 변경
    operations-sorter: alpha # 엔드포인트 정렬 방싣 (알파벳 순)
    tags-sorter: alpha # 태그 정렬 방싣 (알파벳 순)





